version: '3'

services:
  prestashop:
    volumes:
      - ./docker/redis/config.ini:/usr/local/etc/php/conf.d/redis.ini:ro
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}

  redis:
    build:
      context: ./docker/redis
    image: ${REDIS_IMAGE:-extalion/prestashop_redis}
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}
