version: '3'

services:
  prestashop:
    image: ${PRESTASHOP_IMAGE}
    environment:
      - PS_DEV_MODE=0
      - SYMFONY_DEBUG=0
      - SYMFONY_ENV=prod

  nginx:
    image: ${NGINX_IMAGE}

  db:
    image: ${DB_IMAGE}
