version: '3'

services:
    prestashop:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${PRESTASHOP_IMAGE}

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: ${NGINX_IMAGE}
